# texto introdutório

In [4]:
#
import pandas as pd

tabela3 = pd.read_excel('CO_DISTRIB.xlsx')
tabela3.head()
tabela3.tail()

#dados2000_2018<-read.table("BASE_CONSOLIDADA_PBL.csv",header=T,sep=";",na.strings="ND",stringsAsFactors = F)
   # for (i in 5:ncol(dados2000_2018))
   # {
    #dados2000_2018[,i]<-as.numeric(dados2000_2018[,i])
    #}
    #remove(i)
#
#import csv
#tabela4 = csv.reader(open('k-means_base_dados.csv'), delimiter=";")
#tabela4

#tabela4.head()


#
#tabela2 = tabela.drop("Unnamed: 0", axis=1)
#display(tabela2)

,EMPRESA,X18.1.Custos_Operacionais,X18.2.Pessoal,X18.3.Materiais,X18.4.Serv_Terceiros,X18.7.Outros,Part_Perc_P,Part_Perc_M,Part_Perc_ST,Part_Perc_O,cluster
48,NOVA SC (FUSÃƒO),1.224025e+08,5.108146e+07,9.589980e+06,5.486919e+07,5.738302e+06,0.417324,0.078348,0.448268,0.046881,1
49,RGE SUL,6.298107e+08,2.959651e+08,5.244100e+07,2.468306e+08,2.775000e+07,0.469927,0.083265,0.391912,0.044061,2
50,SANTAMARIA,3.771039e+07,2.366933e+07,2.894073e+06,7.596054e+06,1.933642e+06,0.627661,0.076745,0.201431,0.051276,3
51,SULGIPE,3.947589e+07,2.711117e+07,3.529763e+06,5.899543e+06,1.803560e+06,0.686778,0.089416,0.149447,0.045688,3
52,UHENPAL,6.163704e+06,4.245938e+06,4.732459e+05,9.581957e+05,4.203024e+05,0.688862,0.076779,0.155458,0.068190,3

In [1]:
print('teste')

teste